% demo_agent_line.m - 完整 demo（直线轨迹 + Place/Grid cells）
% input: config.m 与 matlab/data/agent_path.csv
% output: 轨迹与发放率相关可视化图（通过 plot_utils 统一生成）
% pos: MATLAB demo 脚本，串联环境/代理/神经元
% 一旦我被更新，务必更新我的开头注释，以及所属的文件夹的md。
%
% 功能：
%   1. 加载配置
%   2. 创建环境和 Agent（从轨迹文件）
%   3. 创建 PlaceCells 和 GridCells
%   4. 运行更新循环
%   5. 调用 plot_utils 进行可视化（轨迹、rate map、时间序列）
%   6. 导出图片（paper-visual 规范）
%
% 使用：
%   >> demo_agent_line

clear; close all; clc;

fprintf('====== RatInABox MATLAB Demo：直线轨迹演示 ======\n\n');

%% 1. 加载配置
fprintf('1. 正在加载配置...\n');
cfg = config();

%% 2. 创建环境和 Agent
fprintf('2. 创建环境与 Agent...\n');

% 环境
env_params = struct(...
    'extent', cfg.env.extent, ...
    'boundary_conditions', cfg.env.boundary_conditions, ...
    'dimensionality', cfg.env.dimensionality, ...
    'dx', cfg.env.dx);
env = EnvironmentStub(env_params);

% Agent（从轨迹文件）
agent = AgentStub(cfg.file.agent_path, env);

fprintf('   环境范围: [%.1f, %.1f] x [%.1f, %.1f] 米\n', ...
    env.extent(1), env.extent(2), env.extent(3), env.extent(4));
fprintf('   轨迹: %d 步, dt = %.3f 秒\n', ...
    length(agent.trajectory.t), agent.dt);

%% 3. 创建 PlaceCells
fprintf('3. 创建 PlaceCells...\n');

pc_params = struct(...
    'n', cfg.place.n, ...
    'description', cfg.place.description, ...
    'widths', cfg.place.widths, ...
    'wall_geometry', cfg.place.wall_geometry, ...
    'min_fr', cfg.neurons.min_fr, ...
    'max_fr', cfg.neurons.max_fr);
pcs = PlaceCells(agent, pc_params);

fprintf('   PlaceCells: 数量 = %d, 宽度 = %.2f 米\n', pcs.n, pcs.params.widths);

%% 4. 创建 GridCells
fprintf('4. 创建 GridCells...\n');

gc_params = struct(...
    'n', cfg.grid.n, ...
    'gridscale', cfg.grid.gridscale, ...
    'orientation', cfg.grid.orientation, ...
    'description', cfg.grid.description, ...
    'min_fr', cfg.neurons.min_fr, ...
    'max_fr', cfg.neurons.max_fr);
gcs = GridCells(agent, gc_params);

fprintf('   GridCells: 数量 = %d, 模块数 = %d\n', gcs.n, length(cfg.grid.gridscale));

%% 5. 运行更新循环
fprintf('5. 运行更新循环...\n');

n_steps = length(agent.trajectory.t);
for i = 1:n_steps
    % 更新神经元
    pcs.update();
    gcs.update();
    
    % 前进一步
    if i < n_steps
        agent.step();
    end
    
    % 进度
    if mod(i, 20) == 0 || i == n_steps
        fprintf('   进度: %d/%d (%.1f%%)\n', i, n_steps, 100*i/n_steps);
    end
end

fprintf('   完成！总时长: %.2f 秒\n', agent.t);

%% 6. 可视化：轨迹
fprintf('6. 绘制 Agent 轨迹...\n');

fig_traj = plot_utils.plot_agent_trajectory(agent, ...
    'fig_name', 'Agent Trajectory', ...
    'fig_position', [40, 40, 600, 600], ...
    'line_width', 1.5, ...
    'marker_size', 6, ...
    'title', 'Agent 轨迹', ...
    'title_fontsize', 12, ...
    'label_fontsize', 11, ...
    'axis_fontsize', 10, ...
    'apply_paper_visual', false);

%% 7. 可视化：PlaceCells rate map
fprintf('7. 绘制 PlaceCells rate map...\n');

% 选取要显示的 PlaceCells 神经元索引数量, 最多为6个或全部（如果不足6个）
chosen = pcs.return_list_of_neurons(min(9, pcs.n)); % chosen 表示被选中的神经元

% 布局相关变量：每行最多3个，将选中的神经元按行列排布
n_cols = min(length(chosen), 3);   % n_cols 表示列数，最大为3
n_rows = ceil(length(chosen) / n_cols);  % n_rows 表示行数，按需要分配

% 变量含义：
% chosen  代表被选中的神经元索引列表
% n_cols  每行的神经元数（列数）
% n_rows  显示神经元所需的总行数


export_path = fullfile(cfg.dir.output, 'placecells_ratemap');
fig_pc_map = plot_utils.plot_rate_map(pcs, ...
    'chosen_neurons', chosen, ...
    'method', 'groundtruth', ...
    'colormap', cfg.plot.colormap, ...
    'colorbar', false, ...
    'layout', 'tiled', ...
    'n_cols', n_cols, ...
    'fig_position', [50, 50, 1200, 400*n_rows], ...
    'fig_name', 'PlaceCells Rate Map', ...
    'title_prefix', '位置细胞', ...
    'title_fontsize', 11, ...
    'label_fontsize', 10, ...
    'apply_paper_visual', false, ...
    'export', export_path);

%% 8. 可视化：GridCells rate map
fprintf('8. 绘制 GridCells rate map...\n');

chosen = gcs.return_list_of_neurons(min(6, gcs.n));
n_cols = min(length(chosen), 3);
n_rows = ceil(length(chosen) / n_cols);

export_path = fullfile(cfg.dir.output, 'gridcells_ratemap');
fig_gc_map = plot_utils.plot_rate_map(gcs, ...
    'chosen_neurons', chosen, ...
    'method', 'groundtruth', ...
    'colormap', cfg.plot.colormap, ...
    'colorbar', false, ...
    'layout', 'tiled', ...
    'n_cols', n_cols, ...
    'fig_position', [100, 100, 1200, 400*n_rows], ...
    'fig_name', 'GridCells Rate Map', ...
    'title_prefix', '网格细胞', ...
    'title_fontsize', 11, ...
    'label_fontsize', 10, ...
    'apply_paper_visual', false, ...
    'export', export_path);

%% 9. 可视化：PlaceCells 时间序列
fprintf('9. 绘制 PlaceCells 时间序列...\n');

export_path = fullfile(cfg.dir.output, 'placecells_timeseries');
fig_pc_ts = plot_utils.plot_rate_timeseries(pcs, ...
    'chosen_neurons', 'all', ...
    'fig_name', 'PlaceCells Timeseries', ...
    'fig_position', [150, 150, 1000, 500], ...
    'xlabel', '时间 (分钟)', ...
    'ylabel', '神经元编号', ...
    'title', '位置细胞发放率时间序列', ...
    'line_width', 1.5, ...
    'axis_fontsize', 10, ...
    'apply_paper_visual', false, ...
    'export', export_path);

%% 10. 完成
fprintf('\n====== Demo 结束 ======\n');
if cfg.plot.export_enabled
    fprintf('图片已导出到: %s\n', cfg.dir.output);
    fprintf('查看文件:\n');
    fprintf('  - placecells_ratemap.png/.eps\n');
    fprintf('  - gridcells_ratemap.png/.eps\n');
    fprintf('  - placecells_timeseries.png/.eps\n');
else
    fprintf('未导出图片（config.plot.export_enabled = false）。\n');
end
